web:
  extends:
    file: compose-common.yml
    service: common
  ports:
    - "3000:3000"
  command: "node web/server.js"
  links:
    - api
rain:
  extends:
    file: compose-common.yml
    service: common
  expose:
    - "3001"
  command: "node weather/rain.js"
  # Since Docker linking can only transmit host, port, and protocol
  # (tcp/udp) information, set a couple of environment variables that
  # the docker-links Bootes plugin will look up from the linked
  # container to find the scheme and path.
  environment:
    BOOTES_SCHEME: http
    BOOTES_PATH: /rain
umbrella:
  extends:
    file: compose-common.yml
    service: common
  expose:
    - "3003"
  command: "node orders/umbrella_orders.js"
  environment:
    BOOTES_SCHEME: http
    BOOTES_PATH: /orders/umbrellas
sms:
  extends:
    file: compose-common.yml
    service: common
  expose:
    - "3002"
  command: "node notification/sms.js"
  environment:
    BOOTES_SCHEME: http
    BOOTES_PATH: /sms
api:
  extends:
    file: compose-common.yml
    service: common
  expose:
    - "3004"
  command: "node orders/api.js"
  links:
    - umbrella:umbrella_orders
    - sms
  environment:
    BOOTES_SCHEME: http
    BOOTES_PATH: /api
